services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_name
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_user", "-d", "postgres_name"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  django:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres_name
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DEBUG=1
    networks:
      - app_network
  celery:
    build: .
    command: ["celery", "-A", "core_app", "worker", "--loglevel=info"]
    depends_on:
      - django
      - redis
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
