# Generated by Django 5.1.7 on 2025-03-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlsvideo',
            name='height',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hlsvideo',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=10),
        ),
        migrations.AddField(
            model_name='hlsvideo',
            name='width',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hlsvideo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
