# Generated by Django 5.1.7 on 2025-03-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0003_hlsvideo_height_hlsvideo_status_hlsvideo_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hlsvideo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hlsvideo',
            name='width',
        ),
    ]
