# Generated by Django 5.1.7 on 2025-03-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0004_remove_hlsvideo_height_remove_hlsvideo_width'),
        ('uploads', '0004_video_audio_bitrate_video_audio_codec_video_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlsvideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hls_video', to='uploads.video'),
        ),
    ]
