# Generated by Django 5.1.7 on 2025-03-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoconfig',
            options={'verbose_name': 'VideoConfig', 'verbose_name_plural': 'VideoConfigs'},
        ),
    ]
