# Generated by Django 5.1.7 on 2025-03-18 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('name', models.CharField(max_length=255)),
                ('video_size', models.BigIntegerField()),
                ('video_duration', models.BigIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео (много)',
            },
        ),
    ]
