# Generated by Django 5.1.7 on 2025-03-23 12:47

import django.db.models.deletion
import uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('video_file', models.FileField(upload_to=uploads.models.Video.video_upload_path)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('duration', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('bitrate', models.PositiveIntegerField(default=0)),
                ('frame_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('audio_codec', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('audio_bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='titles.title')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
