# Generated by Django 5.1.7 on 2025-04-03 14:03

import uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('episode_number', models.PositiveSmallIntegerField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('video_file', models.FileField(max_length=255, upload_to=uploads.models.Video.video_upload_path)),
                ('moderated', models.BooleanField(default=True)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('duration', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('bitrate', models.PositiveIntegerField(default=0)),
                ('frame_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('audio_codec', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('audio_bitrate', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
