# Generated by Django 5.1.7 on 2025-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='moderated',
            field=models.BooleanField(default=True),
        ),
    ]
