# Generated by Django 5.1.7 on 2025-03-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        ('video_configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video_configs.videoconfig'),
        ),
    ]
