# Generated by Django 5.1.7 on 2025-03-21 08:41

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=uploads.models.Video.video_upload_path),
        ),
    ]
