# Generated by Django 5.1.7 on 2025-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='episode_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
