# Generated by Django 5.1.7 on 2025-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_video_status_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_duration',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
