# Generated by Django 5.1.7 on 2025-03-31 13:31

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_video_episode_number_video_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=255, upload_to=uploads.models.Video.video_upload_path),
        ),
    ]
